org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.home=/home/arcanc/.jdks/temurin-25.0.2

minecraft_version=1.26.1
minecraft_version_range=[1.26.1]
neo_version=26.1.0.0-alpha.12+snapshot-7

mod_id=arcslib
mod_name=Arc'sLib
mod_license=Arc's License of Common Sense
mod_version=1.0.0
mod_group_id=com.arcanc.arcslib
