license="${mod_license}"
issueTrackerURL="https://github.com/ArcAnc/PulseLib/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/ArcAnc/PulseLib"
logoFile="logo.png"
#credits=""
authors="ArcAnc"
description='''
Library which allow you to anything with custom models
'''
[[mixins]]
config="${mod_id}.mixins.json"
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    versionRange="[${neo_version},)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
